version: '3.4'

x-build:
  - &build-args
    APP_ENV: 'prod'
    APP_DEBUG: '0'
  - &build-cache
    - ${SYMFONY_IMAGE:-vuongxuongminh/docker-helm-symfony}:prod

services:
  fpm:
    image: ${SYMFONY_IMAGE:-vuongxuongminh/docker-helm-symfony}:prod
    build:
      cache_from: *build-cache
      args:
        << : *build-args