version: '3.4'

x-build:
  - &build-args
    APP_ENV: 'dev'
    APP_DEBUG: '1'
  - &build-cache
    - ${SYMFONY_IMAGE:-vuongxuongminh/docker-helm-symfony}:dev

services:
  setup:
    image: ${SYMFONY_IMAGE:-vuongxuongminh/docker-helm-symfony}:dev
    command: ['setup']
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      cache_from: *build-cache
      args:
        << : *build-args
    environment:
      << : *build-args
    volumes:
      - ./symfony:/symfony:rw

  fpm:
    image: ${PHP_IMAGE:-vuongxuongminh/docker-helm-symfony-php}:dev
    build:
      cache_from: *build-cache
      args:
        << : *build-args
    environment:
      << : *build-args
    volumes:
      - ./symfony:/symfony:rw,cached
      - log-data:/symfony/var/log:rw

  nginx:
    volumes:
      - ./symfony/public:/symfony/public:rw,cached
      - ./docker/nginx/default.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf:ro

  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - promtail
    ports:
      - target: 3000
        published: 3000
        protocol: tcp

  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail
    depends_on:
      - loki
    volumes:
      - log-data:/app/var/log
      - ./docker/promtail:/etc/promtail:ro
    command: -config.file=/etc/promtail/config.yaml

volumes:
  db-data: {}
  grafana-data: {}
  log-data: {}