apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fpm" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
type: Opaque
data:
  APP_SECRET: {{ .Values.global.fpm.secret | b64enc | quote }}