server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: local
    static_configs:
      - targets:
          - localhost
        labels:
          container: supervisor
          __path__: /var/log/supervisor/*log
      - targets:
          - localhost
        labels:
          container: fpm
          __path__: /var/log/fpm/*log
      - targets:
          - localhost
        labels:
          container: nginx
          __path__: /var/log/nginx/*log